Repository ITYL-Bbbbick/beBig_back, pull requests merged in 2024-09, with the labels that each got.

#8 [bebig-119] feat : vo class setting
  src/main/java/beBig/vo/AccountVo.java
  src/main/java/beBig/vo/BadgeVo.java
  src/main/java/beBig/vo/BankVo.java
  src/main/java/beBig/vo/DepositProductVo.java
  src/main/java/beBig/vo/FinTestVo.java
  src/main/java/beBig/vo/FinTypeVo.java
  src/main/java/beBig/vo/LikeHitsVo.java
  src/main/java/beBig/vo/MissionVo.java
  src/main/java/beBig/vo/PersonalDailyMissionVo.java
  src/main/java/beBig/vo/PersonalMonthlyMissionVo.java
  src/main/java/beBig/vo/PostVo.java
  src/main/java/beBig/vo/SavingsProductVo.java
  src/main/java/beBig/vo/TransactionVo.java
  src/main/java/beBig/vo/UserVo.java
  src/main/java/beBig/vo/UtilVo.java
Labels: feat

#10 [bebig-124] chore : 아이디중복체크, 찾기 수정/ 소셜회원가입 추가
  src/main/java/beBig/config/WebConfig.java
  src/main/java/beBig/controller/UserController.java
Labels: chore

#13 Bebig 112 community/set interface
  src/main/java/beBig/config/RootConfig.java
  src/main/java/beBig/config/ServletConfig.java
  src/main/java/beBig/config/WebConfig.java
  src/main/java/beBig/controller/MissionController.java
  src/main/java/beBig/controller/UserController.java
  src/main/java/beBig/form/UserForm.java
  src/main/java/beBig/mapper/CommunityMapper.java
  src/main/java/beBig/mapper/MemberMapper.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/repository/UserRepository.java
  src/main/java/beBig/service/CommunityService.java
  src/main/java/beBig/service/CommunityServiceImp.java
  src/main/java/beBig/service/UserService.java
  src/main/java/beBig/vo/AccountVo.java
  src/main/java/beBig/vo/BadgeVo.java
  src/main/java/beBig/vo/BankVo.java
  src/main/java/beBig/vo/DepositProductVo.java
  src/main/java/beBig/vo/FinTestVo.java
  src/main/java/beBig/vo/FinTypeVo.java
  src/main/java/beBig/vo/LikeHitsVo.java
  src/main/java/beBig/vo/MissionVo.java
  src/main/java/beBig/vo/PersonalDailyMissionVo.java
  src/main/java/beBig/vo/PersonalMonthlyMissionVo.java
  src/main/java/beBig/vo/PostVo.java
  src/main/java/beBig/vo/SavingsProductVo.java
  src/main/java/beBig/vo/TransactionVo.java
  src/main/java/beBig/vo/UserVo.java
  src/main/java/beBig/vo/UtilVo.java
  src/main/resources/beBig/mapper/MapperTemplate.xml
  src/main/resources/beBig/mapper/UserMapper.xml
  src/main/resources/mybatis-config.xml
Labels: feat

#14 [BEBIG-50] :: ID 중복체크 추가
  src/main/java/beBig/controller/UserController.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/UserService.java
  src/main/resources/beBig/mapper/UserMapper.xml
Labels: feat

#19 [BEBIG-97] feat : 아이디 찾기 및 뒷 네자리 *처리
  src/main/java/beBig/config/SecurityConfig.java
  src/main/java/beBig/controller/UserController.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/UserService.java
  src/main/resources/beBig/mapper/UserMapper.xml
Labels: feat

#20 Bebig 62 community/find posts
  src/main/java/beBig/controller/CommunityController.java
  src/main/java/beBig/exception/CommonExceptionAdvice.java
  src/main/java/beBig/exception/NoContentFoundException.java
  src/main/java/beBig/mapper/CommunityMapper.java
  src/main/java/beBig/service/CommunityService.java
  src/main/java/beBig/service/CommunityServiceImp.java
  src/main/resources/beBig/mapper/CommunityMapper.xml
  src/main/resources/mybatis-config.xml
Labels: feat

#22 [bebig-130] refactor : UserService class refactor
  src/main/java/beBig/service/UserService.java
Labels: feat

#24 [Bebig-64] community의 게시글 작성 기능 완성
  .gitignore
  build.gradle
  settings.gradle
  src/main/java/beBig/config/S3Config.java
  src/main/java/beBig/config/ServletConfig.java
  src/main/java/beBig/config/WebConfig.java
  src/main/java/beBig/controller/CommunityController.java
  src/main/java/beBig/exception/AmazonS3UploadException.java
  src/main/java/beBig/mapper/CommunityMapper.java
  src/main/java/beBig/service/CommunityService.java
  src/main/java/beBig/service/CommunityServiceImp.java
  src/main/java/beBig/vo/PostVo.java
  src/main/resources/beBig/mapper/CommunityMapper.xml
Labels: feat

#25 Bebig 129 community/like hits post
  src/main/java/beBig/controller/CommunityController.java
  src/main/java/beBig/dto/LikeRequestDto.java
  src/main/java/beBig/mapper/CommunityMapper.java
  src/main/java/beBig/service/CommunityService.java
  src/main/java/beBig/service/CommunityServiceImp.java
  src/main/resources/beBig/mapper/CommunityMapper.xml
Labels: feat

#26 bebig-44 feat : 회원 관리 기능 구현
  build.gradle
  src/main/java/beBig/config/SecurityConfig.java
  src/main/java/beBig/config/ServletConfig.java
  src/main/java/beBig/config/WebConfig.java
  src/main/java/beBig/controller/UserController.java
  src/main/java/beBig/form/LoginForm.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/CustomUserDetailsService.java
  src/main/java/beBig/service/UserService.java
  src/main/java/beBig/service/jwt/JwtTokenFilter.java
  src/main/java/beBig/service/jwt/JwtTokenProvider.java
  src/main/resources/beBig/mapper/UserMapper.xml
Labels: feat

#28 bebig-134 fix : 이메일 전송 관련 버그 수정
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/UserService.java
Labels: bug

#30 bebig-136 refactor : UserService 인터페이스 생성, 트랜젝션 관리
  src/main/java/beBig/controller/UserController.java
  src/main/java/beBig/service/UserService.java
  src/main/java/beBig/service/UserServiceImp.java
Labels: refactor

#32 [BEBIG-137] feat : 소셜회원가입 페이지에 약관연결
  src/main/java/beBig/controller/UserController.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/UserService.java
  src/main/java/beBig/service/UserServiceImp.java
  src/main/resources/beBig/mapper/UserMapper.xml
Labels: feat

#33 [bebig-132] feat : 홈화면 사용자 정보 불러오기 구현
  src/main/java/beBig/controller/HomeController.java
  src/main/java/beBig/service/HomeService.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/resources/beBig/mapper/UserMapper.xml
Labels: feat

#34 Bebig 135 community/update post
  build.gradle
  src/main/java/beBig/config/SecurityConfig.java
  src/main/java/beBig/config/ServletConfig.java
  src/main/java/beBig/config/WebConfig.java
  src/main/java/beBig/controller/CommunityController.java
  src/main/java/beBig/controller/UserController.java
  src/main/java/beBig/dto/LikeRequestDto.java
  src/main/java/beBig/form/LoginForm.java
  src/main/java/beBig/mapper/CommunityMapper.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/CommunityService.java
  src/main/java/beBig/service/CommunityServiceImp.java
  src/main/java/beBig/service/CustomUserDetailsService.java
  src/main/java/beBig/service/UserService.java
  src/main/java/beBig/service/jwt/JwtTokenFilter.java
  src/main/java/beBig/service/jwt/JwtTokenProvider.java
  src/main/resources/beBig/mapper/CommunityMapper.xml
  src/main/resources/beBig/mapper/UserMapper.xml
Labels: feat

#35 Bebig 47 community
  .gitignore
  build.gradle
  settings.gradle
  src/main/java/beBig/config/S3Config.java
  src/main/java/beBig/config/ServletConfig.java
  src/main/java/beBig/config/WebConfig.java
  src/main/java/beBig/controller/CommunityController.java
  src/main/java/beBig/dto/LikeRequestDto.java
  src/main/java/beBig/exception/AmazonS3UploadException.java
  src/main/java/beBig/exception/CommonExceptionAdvice.java
  src/main/java/beBig/exception/NoContentFoundException.java
  src/main/java/beBig/mapper/CommunityMapper.java
  src/main/java/beBig/service/CommunityService.java
  src/main/java/beBig/service/CommunityServiceImp.java
  src/main/java/beBig/vo/PostVo.java
  src/main/resources/beBig/mapper/CommunityMapper.xml
  src/main/resources/mybatis-config.xml
Labels: feat

#42 [Bebig 133] 커뮤니티 상세페이지 이미지, 좋아요 불러오기 기능
  src/main/java/beBig/controller/HomeController.java
  src/main/java/beBig/controller/UserController.java
  src/main/java/beBig/form/UserForm.java
  src/main/java/beBig/mapper/CommunityMapper.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/CommunityServiceImp.java
  src/main/java/beBig/service/HomeService.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/java/beBig/service/UserService.java
  src/main/java/beBig/service/UserServiceImp.java
  src/main/java/beBig/service/oauth/KakaoOauthService.java
  src/main/java/beBig/vo/PostVo.java
  src/main/resources/beBig/mapper/CommunityMapper.xml
  src/main/resources/beBig/mapper/UserMapper.xml
  src/main/webapp/WEB-INF/views/custom404.jsp
  src/main/webapp/WEB-INF/views/error_page.jsp
  src/main/webapp/WEB-INF/views/header2.jsp
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/social_login.jsp
Labels: feat

#43 [Bebig 145] community에 user fintype dto로 설정
  src/main/java/beBig/controller/MissionController.java
  src/main/java/beBig/controller/UserController.java
  src/main/java/beBig/form/LoginForm.java
  src/main/java/beBig/form/UserForm.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/CommunityServiceImp.java
  src/main/java/beBig/service/CustomUserDetailsService.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/java/beBig/service/MissionService.java
  src/main/java/beBig/service/UserService.java
  src/main/java/beBig/service/UserServiceImp.java
  src/main/java/beBig/vo/PostVo.java
  src/main/java/beBig/vo/UserVo.java
  src/main/resources/beBig/mapper/CommunityMapper.xml
  src/main/resources/beBig/mapper/UserMapper.xml
Labels: enhancement

#44 [bebig-142] refactor : token 구조 및 코드 리펙토링
  src/main/java/beBig/controller/UserController.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/CustomUserDetails.java
  src/main/java/beBig/service/CustomUserDetailsService.java
  src/main/java/beBig/service/UserService.java
  src/main/java/beBig/service/jwt/JwtTokenFilter.java
  src/main/java/beBig/service/jwt/JwtTokenProvider.java
  src/main/resources/beBig/mapper/UserMapper.xml
Labels: refactor

#45 [Bebig-139] 커뮤니티의 delete post 기능 구현
  src/main/java/beBig/controller/CommunityController.java
  src/main/java/beBig/service/CommunityServiceImp.java
  src/main/resources/beBig/mapper/CommunityMapper.xml
Labels: feat

#48 [BEBIG-131] chore : 홈화면 이름가져오기 수정
  src/main/java/beBig/controller/HomeController.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/HomeService.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/resources/beBig/mapper/UserMapper.xml
Labels: chore

#49 Bebig 147 community/find fin type
  src/main/java/beBig/controller/CommunityController.java
  src/main/java/beBig/service/CommunityService.java
  src/main/java/beBig/service/CommunityServiceImp.java
  src/main/resources/beBig/mapper/CommunityMapper.xml
Labels: chore

#51 [BEBIG-131] chore : 내정보 가져오기 핀타입 연결
  src/main/java/beBig/controller/HomeController.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/java/beBig/service/UserServiceImp.java
  src/main/java/beBig/vo/UserVo.java
  src/main/resources/beBig/mapper/UserMapper.xml
Labels: chore

#52 bebig-149 fix : 게시글 fin_type 데이터 추출
  src/main/java/beBig/service/CommunityServiceImp.java
  src/main/resources/beBig/mapper/CommunityMapper.xml
Labels: bug

#53 [Bebig 146] community image 관련 서비스 구현 완료
  src/main/java/beBig/config/HttpRequestConfig.java
  src/main/java/beBig/config/RootConfig.java
  src/main/java/beBig/config/ServletConfig.java
  src/main/java/beBig/controller/CommunityController.java
  src/main/java/beBig/mapper/CommunityMapper.java
  src/main/java/beBig/mapper/ImageMapper.java
  src/main/java/beBig/service/CommunityService.java
  src/main/java/beBig/service/CommunityServiceImp.java
  src/main/java/beBig/service/ImageService.java
  src/main/java/beBig/service/S3ImageServiceImp.java
  src/main/java/beBig/vo/PostVo.java
  src/main/resources/beBig/mapper/CommunityMapper.xml
  src/main/resources/beBig/mapper/ImageMapper.xml
Labels: feat

#55 [bebig-127] fix : 비밀번호 찾기 에러 수정
  src/main/resources/beBig/mapper/UserMapper.xml
Labels: bug

#56 Bebig 153 community/detail list token
  src/main/java/beBig/controller/CommunityController.java
  src/main/java/beBig/controller/HomeController.java
  src/main/java/beBig/controller/MissionController.java
  src/main/java/beBig/controller/UserController.java
  src/main/java/beBig/dto/response/DailyMissionResponseDto.java
  src/main/java/beBig/dto/response/MonthlyMissionResponseDto.java
  src/main/java/beBig/dto/response/PostResponseDto.java
  src/main/java/beBig/mapper/AccountMapper.java
  src/main/java/beBig/mapper/MissionMapper.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/CommunityService.java
  src/main/java/beBig/service/CommunityServiceImp.java
  src/main/java/beBig/service/CustomUserDetails.java
  src/main/java/beBig/service/CustomUserDetailsService.java
  src/main/java/beBig/service/HomeService.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/java/beBig/service/MissionService.java
  src/main/java/beBig/service/MissionServiceImp.java
  src/main/java/beBig/service/UserService.java
  src/main/java/beBig/service/UserServiceImp.java
  src/main/java/beBig/service/jwt/JwtTokenFilter.java
  src/main/java/beBig/service/jwt/JwtTokenProvider.java
  src/main/java/beBig/service/jwt/JwtUtil.java
  src/main/java/beBig/vo/PersonalDailyMissionVo.java
  src/main/java/beBig/vo/PersonalMonthlyMissionVo.java
  src/main/java/beBig/vo/UserVo.java
  src/main/resources/beBig/mapper/AccountMapper.xml
  src/main/resources/beBig/mapper/MissionMapper.xml
  src/main/resources/beBig/mapper/UserMapper.xml
  src/main/resources/mybatis-config.xml
Labels: feat

#57 Bebig 157 community/create post token
  src/main/java/beBig/controller/CommunityController.java
Labels: feat

#60 Bebig 154 community/update delete like token
  src/main/java/beBig/controller/CommunityController.java
  src/main/java/beBig/dto/response/PostResponseDto.java
  src/main/java/beBig/service/CommunityService.java
  src/main/java/beBig/service/CommunityServiceImp.java
Labels: feat

#59 [Bebig-158] swagger 설정 완료
  build.gradle
  src/main/java/beBig/config/ServletConfig.java
  src/main/java/beBig/config/SwaggerConfig.java
  src/main/java/beBig/config/WebConfig.java
Labels: config

#61 Bebig 47 community
  src/main/java/beBig/config/HttpRequestConfig.java
  src/main/java/beBig/config/RootConfig.java
  src/main/java/beBig/config/ServletConfig.java
  src/main/java/beBig/controller/CommunityController.java
  src/main/java/beBig/dto/response/PostResponseDto.java
  src/main/java/beBig/mapper/CommunityMapper.java
  src/main/java/beBig/mapper/ImageMapper.java
  src/main/java/beBig/service/CommunityService.java
  src/main/java/beBig/service/CommunityServiceImp.java
  src/main/java/beBig/service/ImageService.java
  src/main/java/beBig/service/S3ImageServiceImp.java
  src/main/java/beBig/vo/PostVo.java
  src/main/resources/beBig/mapper/CommunityMapper.xml
  src/main/resources/beBig/mapper/ImageMapper.xml
Labels: feat

#63 [BEBIG-164] feat : 적금상품 API 데이터 DB에 저장
  src/main/java/beBig/controller/SavingsApiController.java
  src/main/java/beBig/dto/SavingsProductDto.java
  src/main/java/beBig/mapper/BankMapper.java
  src/main/java/beBig/mapper/SavingsProductMapper.java
  src/main/java/beBig/service/SavingsProductService.java
  src/main/resources/beBig/mapper/BankMapper.xml
  src/main/resources/beBig/mapper/SavingsProductMapper.xml
Labels: feat

#66 [Bebig 59] 월별 소비 분석 spending patterns
  src/main/java/beBig/config/HttpRequestConfig.java
  src/main/java/beBig/config/RootConfig.java
  src/main/java/beBig/config/ServletConfig.java
  src/main/java/beBig/controller/AssetController.java
  src/main/java/beBig/controller/CommunityController.java
  src/main/java/beBig/controller/MissionController.java
  src/main/java/beBig/controller/UserController.java
  src/main/java/beBig/dto/response/PostResponseDto.java
  src/main/java/beBig/dto/response/SpendingPatternsResponseDto.java
  src/main/java/beBig/mapper/AssetMapper.java
  src/main/java/beBig/mapper/CommunityMapper.java
  src/main/java/beBig/mapper/ImageMapper.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/AssetService.java
  src/main/java/beBig/service/AssetServiceImp.java
  src/main/java/beBig/service/CommunityService.java
  src/main/java/beBig/service/CommunityServiceImp.java
  src/main/java/beBig/service/ImageService.java
  src/main/java/beBig/service/S3ImageServiceImp.java
  src/main/java/beBig/service/UserService.java
  src/main/java/beBig/service/UserServiceImp.java
  src/main/java/beBig/vo/PostVo.java
  src/main/resources/beBig/mapper/AssetMapper.xml
  src/main/resources/beBig/mapper/CommunityMapper.xml
  src/main/resources/beBig/mapper/ImageMapper.xml
  src/main/resources/beBig/mapper/UserMapper.xml
  src/main/resources/mybatis-config.xml
Labels: feat

#67 [Bebig-151] feat : codef 자산 불러오기 구현
  src/main/java/beBig/controller/HomeController.java
  src/main/java/beBig/form/AccountForm.java
  src/main/java/beBig/form/CodefResponseForm.java
  src/main/java/beBig/mapper/AccountMapper.java
  src/main/java/beBig/mapper/CodefTokenMapper.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/HomeService.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/java/beBig/service/codef/CodefApiRequester.java
  src/main/java/beBig/service/codef/CodefTokenManager.java
  src/main/java/beBig/service/codef/RSAUtil.java
  src/main/java/beBig/vo/AccountVo.java
  src/main/java/beBig/vo/CodefTokenVo.java
  src/main/resources/beBig/mapper/AccountMapper.xml
  src/main/resources/beBig/mapper/CodefTokenMapper.xml
  src/main/resources/beBig/mapper/UserMapper.xml
Labels: feat

#69 bebig-160 feat : 금융감독원 정기예금 상품 DB에 추가
  src/main/java/beBig/controller/DepositApiController.java
  src/main/java/beBig/mapper/DepositApiMapper.java
  src/main/java/beBig/service/DepositApiService.java
  src/main/java/beBig/service/DepositApiServiceImp.java
  src/main/resources/beBig/mapper/DepositApiMapper.xml
  src/main/resources/mybatis-config.xml
Labels: feat

#70 [bebig-151 feat] : 계좌 정보 DB 추가 기능 구현, 기타 디버그
  src/main/java/beBig/form/CodefResponseForm.java
  src/main/java/beBig/mapper/AccountMapper.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/java/beBig/service/codef/CodefApiRequester.java
  src/main/java/beBig/vo/AccountVo.java
  src/main/resources/beBig/mapper/AccountMapper.xml
  src/main/resources/beBig/mapper/UserMapper.xml
Labels: bug, feat

#72 [Bebig-151] fix: 계좌 연결 구현 완료
  src/main/java/beBig/controller/HomeController.java
  src/main/java/beBig/controller/UserController.java
  src/main/java/beBig/dto/AccountDto.java
  src/main/java/beBig/dto/CodefResponseDto.java
  src/main/java/beBig/dto/LoginDto.java
  src/main/java/beBig/dto/UserDto.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/HomeService.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/java/beBig/service/UserService.java
  src/main/java/beBig/service/UserServiceImp.java
  src/main/java/beBig/service/codef/CodefApiRequester.java
  src/main/java/beBig/vo/AccountVo.java
  src/main/resources/beBig/mapper/AccountMapper.xml
  src/main/resources/mybatis-config.xml
Labels: bug, refactor

#71 [BEBIG-71] feat : mypage 기능구현
  src/main/java/beBig/controller/MyPageController.java
  src/main/java/beBig/dto/response/MyPagePostResponseDto.java
  src/main/java/beBig/dto/response/UserProfileResponseDto.java
  src/main/java/beBig/mapper/MyPageMapper.java
  src/main/java/beBig/service/MyPageService.java
  src/main/java/beBig/service/MyPageServiceImp.java
  src/main/java/beBig/vo/UserProfileResponseVo.java
  src/main/java/beBig/vo/UserRankVo.java
  src/main/java/beBig/vo/UserVo.java
  src/main/resources/beBig/mapper/MyPageMapper.xml
Labels: feat
