Repository ITYL-Bbbbick/beBig_back, pull requests merged in 2024-10, with the labels that each got.

#73 [BEBIG-71] feat : finType정보 UserController에 구현
  src/main/java/beBig/controller/UserController.java
  src/main/java/beBig/dto/response/FinInfoResponseDto.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/UserService.java
  src/main/java/beBig/service/UserServiceImp.java
  src/main/java/beBig/vo/FinTestVo.java
  src/main/resources/beBig/mapper/UserMapper.xml
Labels: feat

#74 [BEBIG-71] chore : fin-type / fin-test 이동 UserController -> HomeController
  src/main/java/beBig/controller/HomeController.java
  src/main/java/beBig/controller/UserController.java
  src/main/java/beBig/mapper/HomeMapper.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/HomeService.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/java/beBig/service/UserService.java
  src/main/java/beBig/service/UserServiceImp.java
  src/main/resources/beBig/mapper/HomeMapper.xml
  src/main/resources/beBig/mapper/UserMapper.xml
Labels: chore

#75 [BEBIG-144] feat : fin-type저장 구현
  src/main/java/beBig/controller/HomeController.java
  src/main/java/beBig/mapper/HomeMapper.java
  src/main/java/beBig/service/HomeService.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/java/beBig/vo/RefreshTokenVo.java
  src/main/resources/beBig/mapper/HomeMapper.xml
Labels: feat

#76 [Bebig 172] 나이별 자산 비교 기능 개발
  src/main/java/beBig/controller/AssetController.java
  src/main/java/beBig/controller/CommunityController.java
  src/main/java/beBig/controller/MissionController.java
  src/main/java/beBig/controller/MyPageController.java
  src/main/java/beBig/controller/UserController.java
  src/main/java/beBig/dto/UserTotalAssetsDto.java
  src/main/java/beBig/dto/request/MissionCompleteRequestDto.java
  src/main/java/beBig/dto/response/FinInfoResponseDto.java
  src/main/java/beBig/dto/response/MyPagePostResponseDto.java
  src/main/java/beBig/dto/response/TotalMissionResponseDto.java
  src/main/java/beBig/dto/response/UserProfileResponseDto.java
  src/main/java/beBig/mapper/AccountMapper.java
  src/main/java/beBig/mapper/AssetMapper.java
  src/main/java/beBig/mapper/MissionMapper.java
  src/main/java/beBig/mapper/MyPageMapper.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/AssetService.java
  src/main/java/beBig/service/AssetServiceImp.java
  src/main/java/beBig/service/CommunityService.java
  src/main/java/beBig/service/CommunityServiceImp.java
  src/main/java/beBig/service/MissionService.java
  src/main/java/beBig/service/MissionServiceImp.java
  src/main/java/beBig/service/MyPageService.java
  src/main/java/beBig/service/MyPageServiceImp.java
  src/main/java/beBig/service/UserService.java
  src/main/java/beBig/service/UserServiceImp.java
  src/main/java/beBig/vo/FinTestVo.java
  src/main/java/beBig/vo/UserProfileResponseVo.java
  src/main/java/beBig/vo/UserRankVo.java
  src/main/java/beBig/vo/UserVo.java
  src/main/resources/beBig/mapper/AssetMapper.xml
  src/main/resources/beBig/mapper/CommunityMapper.xml
  src/main/resources/beBig/mapper/MissionMapper.xml
  src/main/resources/beBig/mapper/MyPageMapper.xml
  src/main/resources/beBig/mapper/UserMapper.xml
  src/main/resources/mybatis-config.xml
Labels: feat

#78 [BEBIG-144] feat : mypage edit 기능 구현
  src/main/java/beBig/controller/MyPageController.java
  src/main/java/beBig/dto/request/MyPageEditRequestDto.java
  src/main/java/beBig/dto/response/MyPageEditResponseDto.java
  src/main/java/beBig/mapper/MyPageMapper.java
  src/main/java/beBig/service/MyPageService.java
  src/main/java/beBig/service/MyPageServiceImp.java
  src/main/java/beBig/service/jwt/JwtTokenFilter.java
  src/main/java/beBig/service/jwt/JwtTokenProvider.java
  src/main/java/beBig/vo/UserVo.java
  src/main/resources/beBig/mapper/MyPageMapper.xml
Labels: feat

#77 bebig-60 feat : 예/적금 상품 추천 기능 구햔
  src/main/java/beBig/controller/AssetController.java
  src/main/java/beBig/controller/DepositApiController.java
  src/main/java/beBig/mapper/AccountMapper.java
  src/main/java/beBig/mapper/AssetMapper.java
  src/main/java/beBig/mapper/DepositApiMapper.java
  src/main/java/beBig/mapper/DepositProductMapper.java
  src/main/java/beBig/mapper/SavingsProductMapper.java
  src/main/java/beBig/service/AssetService.java
  src/main/java/beBig/service/AssetServiceImp.java
  src/main/java/beBig/service/DepositProductServiceImp.java
  src/main/java/beBig/vo/DepositProductVo.java
  src/main/java/beBig/vo/SavingsProductVo.java
  src/main/resources/beBig/mapper/AccountMapper.xml
  src/main/resources/beBig/mapper/DepositProductMapper.xml
  src/main/resources/beBig/mapper/SavingsProductMapper.xml
  src/main/resources/mybatis-config.xml
Labels: feat

#79 [Bebig-177] feat : codef api 거래 내역 저장 및 불러오기
  src/main/java/beBig/controller/HomeController.java
  src/main/java/beBig/dto/AccountRequestDto.java
  src/main/java/beBig/dto/AccountResponseDto.java
  src/main/java/beBig/dto/AccountTransactionDto.java
  src/main/java/beBig/dto/CodefAccountDto.java
  src/main/java/beBig/dto/CodefTransactionRequestDto.java
  src/main/java/beBig/dto/CodefTransactionResponseDto.java
  src/main/java/beBig/mapper/AccountMapper.java
  src/main/java/beBig/service/HomeService.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/java/beBig/service/codef/CodefApiRequester.java
  src/main/java/beBig/vo/TransactionVo.java
  src/main/resources/beBig/mapper/AccountMapper.xml
  src/main/resources/mybatis-config.xml
Labels: feat

#80 [BEBIG-144] refreshToken 수정중 + 뱃지보내기
  src/main/java/beBig/controller/MyPageController.java
  src/main/java/beBig/mapper/MyPageMapper.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/MyPageService.java
  src/main/java/beBig/service/MyPageServiceImp.java
  src/main/java/beBig/service/jwt/JwtTokenProvider.java
  src/main/java/beBig/vo/UserVo.java
  src/main/resources/beBig/mapper/MyPageMapper.xml
  src/main/resources/beBig/mapper/UserMapper.xml
Labels: feat

#81 [Bebig-177] home/save transactions
  src/main/java/beBig/controller/HomeController.java
  src/main/java/beBig/mapper/AccountMapper.java
  src/main/java/beBig/service/HomeService.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/resources/beBig/mapper/AccountMapper.xml
Labels: feat

#83 [BEBIG-144] feat : password-find 기능
  src/main/java/beBig/controller/HomeController.java
  src/main/java/beBig/controller/MyPageController.java
  src/main/java/beBig/mapper/MyPageMapper.java
  src/main/java/beBig/service/MyPageService.java
  src/main/java/beBig/service/MyPageServiceImp.java
  src/main/resources/beBig/mapper/MyPageMapper.xml
Labels: feat

#84 [bebig-183] fix : Dto 관련 에러 및 거래내역 저장 수정
  src/main/java/beBig/controller/UserController.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/java/beBig/service/UserService.java
  src/main/java/beBig/service/UserServiceImp.java
Labels: bug

#85 bebig-178 feat : 총 자산 분석 기능 구현
  src/main/java/beBig/controller/AssetController.java
  src/main/java/beBig/dto/AssetAnalysisDto.java
  src/main/java/beBig/mapper/AssetMapper.java
  src/main/java/beBig/service/AssetService.java
  src/main/java/beBig/service/AssetServiceImp.java
  src/main/resources/beBig/mapper/AssetMapper.xml
Labels: feat

#86 [BEBIG-144] bug : check-passowrd
  src/main/java/beBig/controller/HomeController.java
  src/main/java/beBig/controller/MyPageController.java
  src/main/java/beBig/controller/UserController.java
  src/main/java/beBig/service/jwt/JwtTokenProvider.java
Labels: bug

#87 Bebig 46 analysis
  src/main/java/beBig/controller/AssetController.java
  src/main/java/beBig/controller/DepositApiController.java
  src/main/java/beBig/controller/SavingsApiController.java
  src/main/java/beBig/dto/AssetAnalysisDto.java
  src/main/java/beBig/dto/SavingsProductDto.java
  src/main/java/beBig/dto/UserTotalAssetsDto.java
  src/main/java/beBig/dto/response/SpendingPatternsResponseDto.java
  src/main/java/beBig/mapper/AccountMapper.java
  src/main/java/beBig/mapper/AssetMapper.java
  src/main/java/beBig/mapper/BankMapper.java
  src/main/java/beBig/mapper/DepositProductMapper.java
  src/main/java/beBig/mapper/SavingsProductMapper.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/AssetService.java
  src/main/java/beBig/service/AssetServiceImp.java
  src/main/java/beBig/service/DepositApiService.java
  src/main/java/beBig/service/DepositProductServiceImp.java
  src/main/java/beBig/service/SavingsProductService.java
  src/main/java/beBig/vo/DepositProductVo.java
  src/main/java/beBig/vo/SavingsProductVo.java
  src/main/java/beBig/vo/UserVo.java
  src/main/resources/beBig/mapper/AccountMapper.xml
  src/main/resources/beBig/mapper/AssetMapper.xml
  src/main/resources/beBig/mapper/BankMapper.xml
  src/main/resources/beBig/mapper/DepositProductMapper.xml
  src/main/resources/beBig/mapper/SavingsProductMapper.xml
  src/main/resources/beBig/mapper/UserMapper.xml
  src/main/resources/mybatis-config.xml
Labels: feat

#88 bebig-46 feat : bankUrl 출력
  src/main/java/beBig/controller/HomeController.java
  src/main/java/beBig/vo/DepositProductVo.java
  src/main/java/beBig/vo/SavingsProductVo.java
  src/main/resources/beBig/mapper/AccountMapper.xml
  src/main/resources/beBig/mapper/DepositProductMapper.xml
  src/main/resources/beBig/mapper/SavingsProductMapper.xml
Labels: feat

#90 [BEBIG-188] feat : 마이페이지 공개,비공개 기능구현
  src/main/java/beBig/controller/MyPageController.java
  src/main/java/beBig/mapper/MyPageMapper.java
  src/main/java/beBig/service/MyPageService.java
  src/main/java/beBig/service/MyPageServiceImp.java
  src/main/resources/beBig/mapper/MyPageMapper.xml
Labels: feat

#91 [BEBIG-193] fix : TransactionVo String처리에서 Date처리로 변경에 따른 서비스 코드 에러 수정
  src/main/java/beBig/service/AssetServiceImp.java
Labels: bug

#92 bebig-47 feat : 게시글 조회 닉네임 추가
  src/main/java/beBig/dto/response/PostResponseDto.java
  src/main/java/beBig/service/CommunityServiceImp.java
  src/main/java/beBig/vo/PostVo.java
  src/main/resources/beBig/mapper/CommunityMapper.xml
Labels: feat

#89 [BEBIG-187] feat : refresh-token 로그인 로그아웃 반영
  src/main/java/beBig/controller/TokenController.java
  src/main/java/beBig/controller/UserController.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/UserService.java
  src/main/java/beBig/service/UserServiceImp.java
  src/main/java/beBig/service/jwt/JwtTokenProvider.java
  src/main/java/beBig/service/oauth/KakaoOauthService.java
  src/main/resources/beBig/mapper/UserMapper.xml
Labels: feat

#95 [beBig-201] fix : 계좌 연결 오류 시 에러메시지 수정
  src/main/java/beBig/controller/HomeController.java
  src/main/java/beBig/service/codef/CodefApiRequester.java
Labels: bug

#96 [BEBIG-196] feat : 마이페이지 userId로 구분
  src/main/java/beBig/controller/MyPageController.java
Labels: feat

#97 [beBig-198] feat : Batch + Mission
  build.gradle
  src/main/java/beBig/config/BatchConfig.java
  src/main/java/beBig/config/QuartzConfig.java
  src/main/java/beBig/controller/HomeController.java
  src/main/java/beBig/controller/JobController.java
  src/main/java/beBig/job/AbstractBatchJob.java
  src/main/java/beBig/job/AgeUpdateJob.java
  src/main/java/beBig/job/AssignDailyMissionJob.java
  src/main/java/beBig/job/TransactionUpdateJob.java
  src/main/java/beBig/mapper/AccountMapper.java
  src/main/java/beBig/mapper/MissionMapper.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/AssetServiceImp.java
  src/main/java/beBig/service/HomeService.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/java/beBig/service/MissionService.java
  src/main/java/beBig/service/MissionServiceImp.java
  src/main/java/beBig/service/UserService.java
  src/main/java/beBig/service/UserServiceImp.java
  src/main/resources/beBig/mapper/AccountMapper.xml
  src/main/resources/beBig/mapper/MissionMapper.xml
  src/main/resources/beBig/mapper/UserMapper.xml
Labels: feat

#98 [bebig-207] feat : 계좌 등록 시 60일 간 거래내역 저장
  src/main/java/beBig/config/QuartzConfig.java
  src/main/java/beBig/controller/HomeController.java
  src/main/java/beBig/service/HomeService.java
  src/main/java/beBig/service/HomeServiceImp.java
Labels: feat

#99 [BEBIG-69] chore : 작성한 글 가져올 때 postId 포함하기 위해 코드 수정
  src/main/java/beBig/dto/response/MyPagePostResponseDto.java
  src/main/resources/beBig/mapper/MyPageMapper.xml
Labels: chore

#103 [bebig-218] fix : 거래내역 업데이트 로직 수정
  src/main/java/beBig/config/QuartzConfig.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/resources/beBig/mapper/AccountMapper.xml
Labels: bug

#104 Release/1.1.1 [fix : 거래내역 업데이트 수정]
  src/main/java/beBig/config/QuartzConfig.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/resources/beBig/mapper/AccountMapper.xml
Labels: deploy

#106 [Bebig-221] feat : 미션추가
  src/main/java/beBig/controller/MissionController.java
  src/main/java/beBig/controller/MyPageController.java
  src/main/java/beBig/mapper/MissionMapper.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/MissionService.java
  src/main/java/beBig/service/MissionServiceImp.java
  src/main/java/beBig/service/UserServiceImp.java
  src/main/java/beBig/service/oauth/KakaoOauthService.java
  src/main/resources/beBig/mapper/MissionMapper.xml
  src/main/resources/beBig/mapper/UserMapper.xml
Labels: feat

#108 bebig-215 fix : 좋아요, 최신순 검색필터에 대한 페이지네이션 수정
  src/main/java/beBig/controller/CommunityController.java
  src/main/java/beBig/service/CommunityService.java
  src/main/java/beBig/service/CommunityServiceImp.java
  src/main/resources/beBig/mapper/CommunityMapper.xml
Labels: feat

#112 [Bebig 226] 거래내역 pagination
  src/main/java/beBig/controller/CommunityController.java
  src/main/java/beBig/controller/HomeController.java
  src/main/java/beBig/dto/AccountTransactionDto.java
  src/main/java/beBig/mapper/AccountMapper.java
  src/main/java/beBig/service/HomeService.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/resources/beBig/mapper/AccountMapper.xml
Labels: feat

#113 [Bebig-231] feat : 월간 미션 끝
  src/main/java/beBig/config/QuartzConfig.java
  src/main/java/beBig/controller/MissionController.java
  src/main/java/beBig/controller/MyPageController.java
  src/main/java/beBig/dto/response/MonthlyMissionResponseDto.java
  src/main/java/beBig/mapper/MissionMapper.java
  src/main/java/beBig/service/MissionServiceImp.java
  src/main/java/beBig/vo/PersonalMonthlyMissionVo.java
  src/main/resources/beBig/mapper/MissionMapper.xml
Labels: feat

#114 bebig-251 fix : 계좌 연결 시 바로 저장 후 리스트 반환
  src/main/java/beBig/controller/HomeController.java
  src/main/java/beBig/service/HomeService.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/java/beBig/vo/PersonalMonthlyMissionVo.java
Labels: bug

#117 bebig-252 feat : 거래내역 없을 시 임시 거래내역 생성
  src/main/java/beBig/service/HomeServiceImp.java
Labels: feat

#118 bebig-255 feat : 총 자산 분석 기타 자산 추가
  src/main/java/beBig/dto/AssetAnalysisDto.java
  src/main/java/beBig/mapper/AssetMapper.java
  src/main/java/beBig/service/AssetServiceImp.java
  src/main/resources/beBig/mapper/AssetMapper.xml
Labels: feat

#120 [Bebig-260] fix : 계좌 저장 및 거래내역 에러 수정
  src/main/java/beBig/config/QuartzConfig.java
  src/main/java/beBig/controller/JobController.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/java/beBig/service/codef/CodefApiRequester.java
  src/main/java/beBig/vo/PersonalMonthlyMissionVo.java
  src/main/resources/beBig/mapper/MissionMapper.xml
Labels: bug

#121 [Bebig - 239] feat: 기능 수정 - 자산 순위 비율, 평균 자산 기능
  src/main/java/beBig/dto/UserTotalAssetsDto.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/AssetServiceImp.java
  src/main/java/beBig/service/UserServiceImp.java
  src/main/resources/beBig/mapper/UserMapper.xml
Labels: feat

#122 [BEBIG-266] feat : 회원가입 연령대 미반영 구현
  src/main/java/beBig/dto/UserDto.java
  src/main/java/beBig/service/UserServiceImp.java
Labels: feat

#123 [bebig-260] feat : QuartzConfig 및 미션 수정, 거래내역 저장 관련 수정
  src/main/java/beBig/config/QuartzConfig.java
  src/main/java/beBig/mapper/MissionMapper.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/java/beBig/service/MissionServiceImp.java
  src/main/resources/beBig/mapper/MissionMapper.xml
Labels: feat

#124 Release/1.5.0
  src/main/java/beBig/config/QuartzConfig.java
  src/main/java/beBig/dto/UserDto.java
  src/main/java/beBig/dto/UserTotalAssetsDto.java
  src/main/java/beBig/mapper/MissionMapper.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/AssetServiceImp.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/java/beBig/service/MissionServiceImp.java
  src/main/java/beBig/service/UserServiceImp.java
  src/main/java/beBig/service/codef/CodefApiRequester.java
  src/main/java/beBig/vo/PersonalMonthlyMissionVo.java
  src/main/resources/beBig/mapper/MissionMapper.xml
  src/main/resources/beBig/mapper/UserMapper.xml
Labels: deploy

#126 Release/1.5.3
  src/main/java/beBig/config/QuartzConfig.java
Labels: deploy

#129 Release/1.6.1
  src/main/java/beBig/controller/HomeController.java
  src/main/java/beBig/mapper/AccountMapper.java
  src/main/java/beBig/mapper/AssetMapper.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/AssetServiceImp.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/java/beBig/vo/AssetUserBalanceVo.java
  src/main/resources/beBig/mapper/AccountMapper.xml
  src/main/resources/beBig/mapper/AssetMapper.xml
  src/main/resources/beBig/mapper/UserMapper.xml
Labels: deploy

#130 [BEBIG-284] fix : 사용자 상위 퍼센트 계산
  src/main/java/beBig/controller/UserController.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/MyPageServiceImp.java
  src/main/resources/beBig/mapper/MyPageMapper.xml
  src/main/resources/beBig/mapper/UserMapper.xml
Labels: chore

#131 [bebig-283] feat : 거래내역 저장 기간 2개월 -> 1년
  src/main/java/beBig/mapper/AccountMapper.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/resources/beBig/mapper/AccountMapper.xml
Labels: feat

#133 Release/1.7.0
  src/main/java/beBig/controller/MissionController.java
  src/main/java/beBig/controller/UserController.java
  src/main/java/beBig/mapper/AccountMapper.java
  src/main/java/beBig/mapper/UserMapper.java
  src/main/java/beBig/service/AssetServiceImp.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/java/beBig/service/MyPageServiceImp.java
  src/main/java/beBig/vo/DepositProductVo.java
  src/main/java/beBig/vo/SavingsProductVo.java
  src/main/resources/beBig/mapper/AccountMapper.xml
  src/main/resources/beBig/mapper/DepositProductMapper.xml
  src/main/resources/beBig/mapper/MyPageMapper.xml
  src/main/resources/beBig/mapper/SavingsProductMapper.xml
  src/main/resources/beBig/mapper/UserMapper.xml
Labels: deploy

#134 Release/1.9.0
  src/main/java/beBig/config/BatchConfig.java
  src/main/java/beBig/config/QuartzConfig.java
  src/main/java/beBig/service/HomeService.java
  src/main/java/beBig/service/HomeServiceImp.java
  src/main/resources/beBig/mapper/DepositProductMapper.xml
  src/main/resources/beBig/mapper/SavingsProductMapper.xml
Labels: deploy
